version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_HOST=auth-service # This should match the service name
      - AUTH_SERVICE_PORT=3001
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev api-gateway
    depends_on:
      - auth-service
    networks:
      - microservice-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-service
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/auth
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev auth-service
    depends_on:
      - mongodb
    networks:
      - microservice-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  mongodb_data:
